config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end
  #index action
  get 'products', to: 'products#index', as: 'products'
  #show action
  get 'products/:id', to: 'products#show', as: 'product', id: /\d+/
  #new action
  get 'products/new', to: 'products#new', as: 'new_product'
  #create action
  post 'products', to: 'products#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence: :true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :price, presence: true
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController

    def index
      all_posts = Post.all
      render json: all_posts
    end

    def create
      post = Post.create(post_params)
      if post.save
        render json: post
      else
        render json: { error: post.errors.full_messages }, status: 422
        end
    end

    def show
      post = Post.find(params[:id])
      render json: post
    end

    def update
      post = Post.find(params[:id])
      post.update(post_params)
      render json: post
    end

    def destroy
      Post.destroy(params[:id])
      head :ok
    end

    private

    def post_params
      params.permit(:title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  #load the specific product id
  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path(@product)
    else
      render :new
    end
  end
  private

  def product_params
    params.require(:product).permit(:title, :description, :stock_quantity, :price)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_react' %>
  </head>

  <body>

  <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%#= javascript_pack_tag 'hello_react' %>
<h1>Home Page</h1>
<%#= link_to "Create a new Product", new_product_path %>

<%#= @products.each do |product| %>
<!--  <h2> <%#= link_to product.title, products_path(product) %></h2>-->
<!--  <p> <%#= product.description %></p>-->
<!--  <p> Price: <%#= number_to_currency product.price %></p>-->
<%#end %>

app/views/products/new.html.erb
<h2> Add a new Product</h2>

<%= form_for @product, remote: false do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title%>

  <%= f.label :description %>
  <%= f.text_area :description%>

  <%= f.label :stock_quantity %>
  <%= f.text_field :stock_quantity%>

  <%= f.label :price %>
  <%= f.text_field :price%>

  <%= f.submit %>
<%end %>

app/views/products/show.html.erb
<%= link_to "Glutten Goods", products_path %>

<h2> <%= @product.title %></h2>
<p> <%= @product.description %></p>
<p> Price: <%= number_to_currency @product.price %></p>